# Generated by Django 5.1.7 on 2025-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='products')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('lte_exists', models.BooleanField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
            ],
        ),
    ]
